[versions]
# Plugins
kotlin = "2.3.0"
gradlePluginAndroid = "8.11.2"
gradlePluginKsp = "2.3.5"

# Android
android-compileSdk = "36"
android-targetSdk = "36"
android-minSdk = "30"

# Libraries
androidxActivity = "1.12.3"
androidxCore = "1.17.0"
androidxEspresso = "3.7.0"
androidxLifecycle = "2.9.6"
androidxStartup = "1.2.0"
androidxTestExt = "1.3.0"
composeHotReload = "1.0.0"
composeMultiplatform = "1.10.0"
composeUnstyled = "1.49.6"
junit = "4.13.2"
kotlinxCoroutines = "1.10.2"


[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxEspresso" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidxStartup" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
composeunstyled-primitives = { module = "com.composables:composeunstyled-primitives", version.ref = "composeUnstyled" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinxCoroutines" }


[plugins]
android-application = { id = "com.android.application", version.ref = "gradlePluginAndroid" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "gradlePluginAndroid" }
android-library = { id = "com.android.library", version.ref = "gradlePluginAndroid" }
android-lint = { id = "com.android.lint", version.ref = "gradlePluginAndroid" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
